spring.application.name=backend
server.port=8080

# C?u h�nh MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3307/bookstore
spring.datasource.username=root
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


spring.devtools.restart.enabled=false

book.app.jwtSecret=${JWT_SECRET:LAP_TRINH_WWW_JAVA_BACKEND_SPRING_BOOT_BOOKS_STORE}
book.app.jwtExpirationMs=86400000
