spring.application.name=backend
server.port=8080

# C?u h�nh MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/bookstore
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Flyway Database Migrations
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true


spring.devtools.restart.enabled=false

book.app.jwtSecret=LAP_TRINH_WWW_JAVA_BACKEND_SPRING_BOOT_BOOKS_STORE
book.app.jwtExpirationMs=86400000

# Cau hinh Spring AI cho Gemini
gemini.enabled=true
gemini.api.key=AIzaSyBuhuCuBWQ90BA6AM0c6XIuu0a99wSdqPw

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maithanhhaiquan2004@gmail.com
spring.mail.password=ewin tbqs pnhx voqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# ===== VNPAY Sandbox =====
payment.vnpay.tmn-code=RDMBOAN3
payment.vnpay.hash-secret=JZ10NLMJRBLUWEPT92A3UDMTGHC5P317
payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.api-version=2.1.0
payment.vnpay.return-url=http://localhost:3000/payment/vnpay/return
payment.vnpay.curr-code=VND

# ===== Cloudinary Configuration =====
cloudinary.cloud-name=dr7iloxoa
cloudinary.api-key=726541573622412
cloudinary.api-secret=fphMJuN_g1KGWd7SyDapDTryP0A

# ===== MoMo Test Environment =====
payment.momo.partner-code=MOMOBKUN20180529
payment.momo.access-key=klm05TvNBzhg7h7j
payment.momo.secret-key=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
payment.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
payment.momo.redirect-url=http://localhost:3000/payment/momo/return
payment.momo.ipn-url=http://localhost:8080/api/payments/momo/ipn
payment.momo.request-type=captureWallet

paypal.mode=sandbox
paypal.client.id=AWuXaji91ZBIHvYz2bUCt2eSVWs_bBPETzVj4huU2KeiDrE32XoDvh1PUQ2FQxuZ9iW2mINxtzyFFs-z
paypal.client.secret=EEM3Grc7VupTqDHhdJLuxrkNlvwapTSHfBF5Nw-j6OE9X3ERjPgTYvajwliwKfCypmQ4teXqanu3VktH

